# -*- coding: utf-8 -*-
"""ICT1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmndwVY3j1H6x6aCKc7QuUM-uzECO9yp
"""





a=10
b=20
c=a+b
print(c)